### ISSUE TITLE
ES6 Error on import

### ISSUE THREAD

**Issue by cruzlutor** [Nazariglez/pixi-keyboard#3]
I get error on ES6, Im using babel-preset-latest

When I import the npm module 
`import keyboard from 'pixi-keyboard'` 

I get this
`Uncaught TypeError: Cannot read property 'utils' of undefined`

The piece of code 
`f["default"].utils.EventEmitter`

**Comment by Turbine1991** [comment]
I've made a fix. Unfortunately there were a few more issues.

I've made a new package to handle keyboard & mouse inputs:
https://www.npmjs.com/package/pixi.js-keyboard
https://www.npmjs.com/package/pixi.js-mouse

Technically neither of them depend on pixi.js, however the mouse uses the canvas to work out the relative/local mouse position.

**Comment by Nazariglez** [comment]
Should be fixed with #4
